name: playboy
description: A flutter video player.
publish_to: 'none'

version: 0.25.2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # File System
  path: ^1.8.3
  path_provider: ^2.1.1
  file_picker: ^8.3.1
  json_annotation: ^4.8.1

  # Desktop Window Control
  window_manager: ^0.3.8
  macos_window_utils: ^1.6.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274

  # Media
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4

  # Misc
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.7.1

flutter:
  assets:
    - res/contributors/
    - l10n/
  uses-material-design: true
  generate: true
