name: playboy
description: A flutter video player.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  squiggly_slider: ^1.0.5

  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  crypto: ^3.0.3

  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  provider: ^6.1.1
  path: ^1.8.3
  file_picker: ^8.3.1

  window_manager: ^0.3.8
  url_launcher: ^6.2.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274
  
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4

  process_run: ^1.1.0

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  msix: ^3.16.7

flutter_launcher_icons:
  android: true
  image_path_android: "res/images/icon512.png"
  adaptive_icon_background: "res/images/icon_bg.png"
  adaptive_icon_foreground: "res/images/icon_fg.png"
  adaptive_icon_monochrome: "res/images/icon_mono.png"
  windows:
    generate: true
    image_path: "res/images/icon512.png"
    icon_size: 256
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:
  assets:
    - res/contributors/
  uses-material-design: true
  generate: true

msix_config:
  display_name: Playboy Player
  identity_name: YuiHrsw.PlayboyPlayer
  msix_version: 1.24.0.0
  logo_path: res/images/icon512.png
  trim_logo: false
  file_extension: .avi, .flv, .mkv, .mov, .mp4, .mpeg, .webm, .wmv, .aac, .midi, .mp3, .ogg, .wav
flutter_intl:
  enabled: true